namespace: aml-shuri-aws-prod
cluster: "aml-shuri-prod-west-2"
replicaCount: 3
aws:
  enabled: true
image:
  registry: docker.apple.com
  repository: shuri
  name: stargate
  tag: latest
  pullPolicy: Always

grpc:
  enabled: true
  service:
    port: 8082
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 11M
    nginx.ingress.kubernetes.io/proxy-body-size: 11M
    kubernetes.io/ingress.class: ingress-nginx-dhari
  hosts:
    - host: stargate-aws-grpc.apple.com
      http:
        paths:
          - backend:
              service:
                name: stargate
                port:
                  number: 8082
            path: /
            pathType: ImplementationSpecific
    - host: stargate-aws-grpc.g.apple.com
      http:
        paths:
          - backend:
              service:
                name: stargate
                port:
                  number: 8082
            path: /
            pathType: ImplementationSpecific
    - host: stargate-grpc.apple.com
      http:
        paths:
          - backend:
              service:
                name: stargate
                port:
                  number: 8082
            path: /
            pathType: ImplementationSpecific
    - host: stargate-grpc.g.apple.com
      http:
        paths:
          - backend:
              service:
                name: stargate
                port:
                  number: 8082
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - stargate-aws-grpc.apple.com
        - stargate-aws-grpc.g.apple.com
        - stargate-grpc.apple.com
        - stargate-grpc.g.apple.com
      secretName: stargate-platform.apple.com.tls
mongodb:
  enabled: true
  namespace: isdataservices
  cluster: aml-shuri-test-west-2
thrift:
  enabled: false
  service:
    port: 8081

imdg:
  enabled: false

app:
  environment: PROD
  applicationProperties:
    APP_MODE: PROD
    PLATFORM_APPLICATION_ID: shuri
    PLATFORM_PROCESS_NAME: us-west-1a
    PLATFORM_WORK_UNIT_ID: pod1
    PLATFORM_JOB_ID: hostname
    PLATFORM_SHORT_INSTANCE_ID: stargate-prod
    HUBBLE_TCP_URL: "tcp://hubble-tcp-publish-corp.apple.com:9898"
    READINESS_ENABLE_CHECK: true
    LIVENESS_ENABLE_CHECK: true
    GSLB_ENABLE_CHECK: true
    APP_DB_INSTANCES: "ma4-mi2p-lmdb04.corp.apple.com:10909,ma4-mi2p-lmdb05.corp.apple.com:10909,ma4-mi2p-lmdb06.corp.apple.com:10909,msc2-maasp-mgt01-lmdb04.msc.apple.com:10909,msc2-maasp-mgt01-lmdb05.msc.apple.com:10909,msc2-maasp-mgt01-lmdb02.msc.apple.com:10909,rn-maasp-mgt01-lmdb12.rno.apple.com:10911"
    APP_DB_NAME: "stargate"
    APP_DB_USER: "C=US,ST=California,O=Apple Inc.,OU=management:idms.group.1462913,CN=stargate.shuri1p.apple.com"
    APP_DB_KEYSTORE_ALIAS: "stargate.shuri1p.apple.com"
    APP_DB_KEYSTORE_PATH: "/app/keystore/stargate.jks"
    APP_GITHUB_CLIENT_ID: athenaml-sa
    APP_ACS_SPARK_PROJECT_ID: 3gxn0eiyita4
    APP_ACS_SPARK_SOURCE_ID: dq8usucn5fdo
    APP_ACS_SPARK_NAMESPACE_ID: 01xzbi6zcqsx
    APP_GRPC_SERVICE: "stargate-grpc.g.apple.com:443"
    APP_K8S_SPLUNK_FORWARDER_VERSION: "8.2.5"
  secretName: "aml-stargate-secret-prod"

nodeSelector:
  node.kubernetes.io/instance-type: r5a.12xlarge

initContainers:
  vault:
    enabled: false
    secretName: "aml-stargate-vault-secret-prod"
    kubernetesServicePort: 6442
  certd:
    enabled: false
  whisper:
    enabled: false
    env: prod
  appconfig:
    enabled: true
    secret: appconfig-prod
    env:
      - name: spring.cloud.config.name
        value: M00637
      - name: spring.cloud.config.label
        value: PROD_WEST2
      - name: spring.cloud.config.profile
        value: SHURI_AWS
      - name: appconfig.init-container.property.download.enabled
        value: "true"
      - name: appconfig.init-container.property.download.path
        value: "/app-config"
      - name: appconfig.init-container.property.download.fileName
        value: "app.secrets"
      - name: appconfig.init-container.resource.enabled
        value: "true"
      - name: appconfig.init-container.resource.defaultPath
        value: "/app-config"
      - name: appconfig.init-container.resource.fileNames
        value: "keystore.jks,stargate.jks"
idms:
  environment: "prod"

splunk:
  enabled: true
  index: "stargate"
  clusterName: "iag_prod"
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 500Mi
ingress:
  enabled: true
  awsAnnotations:
    kubernetes.io/ingress.class: ingress-nginx-dhari
    nginx.ingress.kubernetes.io/client-body-buffer-size: 11M
    nginx.ingress.kubernetes.io/proxy-body-size: 11M
  rules:
    - host: stargate-aws.apple.com
      http:
        paths:
          - backend:
              service:
                name: stargate
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
    - host: stargate-aws.g.apple.com
      http:
        paths:
          - backend:
              service:
                name: stargate
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
    - host: stargate-platform.apple.com
      http:
        paths:
          - backend:
              service:
                name: stargate
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
    - host: stargate-platform.g.apple.com
      http:
        paths:
          - backend:
              service:
                name: stargate
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - stargate-aws.apple.com
        - stargate-aws.g.apple.com
        - stargate-platform.apple.com
        - stargate-platform.g.apple.com
      secretName: stargate-platform.apple.com.tls
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5

shuria3:
  enabled: false
  app:
    enabled: false
    javaVMArgs: "-DI3_ENV=PROD-HTTPS"
    secretName: "aml-shuri-a3-secret-prod"
  readinessProbe:
    enabled: true
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 1
  livenessProbe:
    enabled: true
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 1

readinessProbe:
  enabled: true
  #  initialDelaySeconds: 60
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  httpGet:
    path: /readiness
    port: 8080
livenessProbe:
  enabled: true
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  failureThreshold: 3
  httpGet:
    path: /health

# revisionHistoryLimit: 2
deploymentStrategy: { }
#  type: RollingUpdate
#  rollingUpdate:
#    maxSurge: 1
#    maxUnavailable: 0

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: 1
