apiVersion: apps/v1
kind: Deployment
metadata:
  name: stargate-observability-agent
  namespace: stargate-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stargate-observability-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stargate-observability-agent
    spec:
      containers:
        - name: observability
          image: docker.apple.com/aml/stargate-observability-agent:5825e68a083c
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: stargate-operator
          env:
            - name: APP_ID
              value: '182562'
            - name: APP_MODE
              value: 'DEV'
            - name: JAVA_OPTS
              value: ' -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600