# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stargate.rpc.proto.sgrm_pb2 as sgrm__pb2


class ResourceManagerProtoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.fetchA3Token = channel.unary_unary(
                '/ResourceManagerProtoService/fetchA3Token',
                request_serializer=sgrm__pb2.A3TokenRequest.SerializeToString,
                response_deserializer=sgrm__pb2.A3TokenResponse.FromString,
                )
        self.validateA3Token = channel.unary_unary(
                '/ResourceManagerProtoService/validateA3Token',
                request_serializer=sgrm__pb2.A3TokenValidateRequest.SerializeToString,
                response_deserializer=sgrm__pb2.A3TokenValidateResponse.FromString,
                )
        self.publishError = channel.unary_unary(
                '/ResourceManagerProtoService/publishError',
                request_serializer=sgrm__pb2.ErrorRequest.SerializeToString,
                response_deserializer=sgrm__pb2.ErrorResponse.FromString,
                )
        self.readAttributes = channel.unary_unary(
                '/ResourceManagerProtoService/readAttributes',
                request_serializer=sgrm__pb2.AttributesReadRequest.SerializeToString,
                response_deserializer=sgrm__pb2.AttributesReadResponse.FromString,
                )
        self.bulkReadAttributes = channel.unary_unary(
                '/ResourceManagerProtoService/bulkReadAttributes',
                request_serializer=sgrm__pb2.AttributesBulkReadRequest.SerializeToString,
                response_deserializer=sgrm__pb2.AttributesReadResponse.FromString,
                )
        self.readAttributesFields = channel.unary_unary(
                '/ResourceManagerProtoService/readAttributesFields',
                request_serializer=sgrm__pb2.AttributesReadFieldsRequest.SerializeToString,
                response_deserializer=sgrm__pb2.AttributesReadResponse.FromString,
                )
        self.readAttributesRangeFields = channel.unary_unary(
                '/ResourceManagerProtoService/readAttributesRangeFields',
                request_serializer=sgrm__pb2.AttributesReadRangeFieldsRequest.SerializeToString,
                response_deserializer=sgrm__pb2.AttributesReadResponse.FromString,
                )
        self.writeAttributes = channel.unary_unary(
                '/ResourceManagerProtoService/writeAttributes',
                request_serializer=sgrm__pb2.AttributesWriteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.CompletionResponse.FromString,
                )
        self.bulkWriteAttributes = channel.unary_unary(
                '/ResourceManagerProtoService/bulkWriteAttributes',
                request_serializer=sgrm__pb2.AttributesBulkWriteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.BulkOpCompletionResponse.FromString,
                )
        self.writeAttributesField = channel.unary_unary(
                '/ResourceManagerProtoService/writeAttributesField',
                request_serializer=sgrm__pb2.AttributesWriteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.CompletionResponse.FromString,
                )
        self.writeAttributesFields = channel.unary_unary(
                '/ResourceManagerProtoService/writeAttributesFields',
                request_serializer=sgrm__pb2.AttributesWriteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.CompletionResponse.FromString,
                )
        self.deleteAttributes = channel.unary_unary(
                '/ResourceManagerProtoService/deleteAttributes',
                request_serializer=sgrm__pb2.AttributesDeleteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.CompletionResponse.FromString,
                )
        self.bulkDeleteAttributes = channel.unary_unary(
                '/ResourceManagerProtoService/bulkDeleteAttributes',
                request_serializer=sgrm__pb2.AttributesBulkDeleteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.BulkOpCompletionResponse.FromString,
                )
        self.readLookup = channel.unary_unary(
                '/ResourceManagerProtoService/readLookup',
                request_serializer=sgrm__pb2.LookupReadRequest.SerializeToString,
                response_deserializer=sgrm__pb2.LookupReadResponse.FromString,
                )
        self.bulkReadLookup = channel.unary_unary(
                '/ResourceManagerProtoService/bulkReadLookup',
                request_serializer=sgrm__pb2.LookupBulkReadRequest.SerializeToString,
                response_deserializer=sgrm__pb2.LookupReadResponse.FromString,
                )
        self.writeLookup = channel.unary_unary(
                '/ResourceManagerProtoService/writeLookup',
                request_serializer=sgrm__pb2.LookupWriteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.CompletionResponse.FromString,
                )
        self.bulkWriteLookup = channel.unary_unary(
                '/ResourceManagerProtoService/bulkWriteLookup',
                request_serializer=sgrm__pb2.LookupBulkWriteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.BulkOpCompletionResponse.FromString,
                )
        self.deleteLookup = channel.unary_unary(
                '/ResourceManagerProtoService/deleteLookup',
                request_serializer=sgrm__pb2.LookupDeleteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.CompletionResponse.FromString,
                )
        self.bulkDeleteLookup = channel.unary_unary(
                '/ResourceManagerProtoService/bulkDeleteLookup',
                request_serializer=sgrm__pb2.LookupBulkDeleteRequest.SerializeToString,
                response_deserializer=sgrm__pb2.BulkOpCompletionResponse.FromString,
                )
        self.readShuriOfsFeature = channel.unary_unary(
                '/ResourceManagerProtoService/readShuriOfsFeature',
                request_serializer=sgrm__pb2.ShuriOfsReadFeatureRequest.SerializeToString,
                response_deserializer=sgrm__pb2.ShuriOfsReadResponse.FromString,
                )
        self.readShuriOfsFeatureGroups = channel.unary_unary(
                '/ResourceManagerProtoService/readShuriOfsFeatureGroups',
                request_serializer=sgrm__pb2.ShuriOfsReadFeatureGroupsRequest.SerializeToString,
                response_deserializer=sgrm__pb2.ShuriOfsReadResponse.FromString,
                )
        self.writeShuriOfsFeatureGroup = channel.unary_unary(
                '/ResourceManagerProtoService/writeShuriOfsFeatureGroup',
                request_serializer=sgrm__pb2.ShuriOfsWriteFeatureGroupRequest.SerializeToString,
                response_deserializer=sgrm__pb2.CompletionStatus.FromString,
                )
        self.deleteShuriOfsFeatureField = channel.unary_unary(
                '/ResourceManagerProtoService/deleteShuriOfsFeatureField',
                request_serializer=sgrm__pb2.ShuriOfsDeleteFeatureFieldRequest.SerializeToString,
                response_deserializer=sgrm__pb2.CompletionStatus.FromString,
                )


class ResourceManagerProtoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def fetchA3Token(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def validateA3Token(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def publishError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readAttributes(self, request, context):
        """Attributes Service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bulkReadAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readAttributesFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readAttributesRangeFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def writeAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bulkWriteAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def writeAttributesField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def writeAttributesFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bulkDeleteAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readLookup(self, request, context):
        """Lookup Service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bulkReadLookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def writeLookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bulkWriteLookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteLookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bulkDeleteLookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readShuriOfsFeature(self, request, context):
        """Shuri Ofs Service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readShuriOfsFeatureGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def writeShuriOfsFeatureGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteShuriOfsFeatureField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourceManagerProtoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'fetchA3Token': grpc.unary_unary_rpc_method_handler(
                    servicer.fetchA3Token,
                    request_deserializer=sgrm__pb2.A3TokenRequest.FromString,
                    response_serializer=sgrm__pb2.A3TokenResponse.SerializeToString,
            ),
            'validateA3Token': grpc.unary_unary_rpc_method_handler(
                    servicer.validateA3Token,
                    request_deserializer=sgrm__pb2.A3TokenValidateRequest.FromString,
                    response_serializer=sgrm__pb2.A3TokenValidateResponse.SerializeToString,
            ),
            'publishError': grpc.unary_unary_rpc_method_handler(
                    servicer.publishError,
                    request_deserializer=sgrm__pb2.ErrorRequest.FromString,
                    response_serializer=sgrm__pb2.ErrorResponse.SerializeToString,
            ),
            'readAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.readAttributes,
                    request_deserializer=sgrm__pb2.AttributesReadRequest.FromString,
                    response_serializer=sgrm__pb2.AttributesReadResponse.SerializeToString,
            ),
            'bulkReadAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.bulkReadAttributes,
                    request_deserializer=sgrm__pb2.AttributesBulkReadRequest.FromString,
                    response_serializer=sgrm__pb2.AttributesReadResponse.SerializeToString,
            ),
            'readAttributesFields': grpc.unary_unary_rpc_method_handler(
                    servicer.readAttributesFields,
                    request_deserializer=sgrm__pb2.AttributesReadFieldsRequest.FromString,
                    response_serializer=sgrm__pb2.AttributesReadResponse.SerializeToString,
            ),
            'readAttributesRangeFields': grpc.unary_unary_rpc_method_handler(
                    servicer.readAttributesRangeFields,
                    request_deserializer=sgrm__pb2.AttributesReadRangeFieldsRequest.FromString,
                    response_serializer=sgrm__pb2.AttributesReadResponse.SerializeToString,
            ),
            'writeAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.writeAttributes,
                    request_deserializer=sgrm__pb2.AttributesWriteRequest.FromString,
                    response_serializer=sgrm__pb2.CompletionResponse.SerializeToString,
            ),
            'bulkWriteAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.bulkWriteAttributes,
                    request_deserializer=sgrm__pb2.AttributesBulkWriteRequest.FromString,
                    response_serializer=sgrm__pb2.BulkOpCompletionResponse.SerializeToString,
            ),
            'writeAttributesField': grpc.unary_unary_rpc_method_handler(
                    servicer.writeAttributesField,
                    request_deserializer=sgrm__pb2.AttributesWriteRequest.FromString,
                    response_serializer=sgrm__pb2.CompletionResponse.SerializeToString,
            ),
            'writeAttributesFields': grpc.unary_unary_rpc_method_handler(
                    servicer.writeAttributesFields,
                    request_deserializer=sgrm__pb2.AttributesWriteRequest.FromString,
                    response_serializer=sgrm__pb2.CompletionResponse.SerializeToString,
            ),
            'deleteAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteAttributes,
                    request_deserializer=sgrm__pb2.AttributesDeleteRequest.FromString,
                    response_serializer=sgrm__pb2.CompletionResponse.SerializeToString,
            ),
            'bulkDeleteAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.bulkDeleteAttributes,
                    request_deserializer=sgrm__pb2.AttributesBulkDeleteRequest.FromString,
                    response_serializer=sgrm__pb2.BulkOpCompletionResponse.SerializeToString,
            ),
            'readLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.readLookup,
                    request_deserializer=sgrm__pb2.LookupReadRequest.FromString,
                    response_serializer=sgrm__pb2.LookupReadResponse.SerializeToString,
            ),
            'bulkReadLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.bulkReadLookup,
                    request_deserializer=sgrm__pb2.LookupBulkReadRequest.FromString,
                    response_serializer=sgrm__pb2.LookupReadResponse.SerializeToString,
            ),
            'writeLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.writeLookup,
                    request_deserializer=sgrm__pb2.LookupWriteRequest.FromString,
                    response_serializer=sgrm__pb2.CompletionResponse.SerializeToString,
            ),
            'bulkWriteLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.bulkWriteLookup,
                    request_deserializer=sgrm__pb2.LookupBulkWriteRequest.FromString,
                    response_serializer=sgrm__pb2.BulkOpCompletionResponse.SerializeToString,
            ),
            'deleteLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteLookup,
                    request_deserializer=sgrm__pb2.LookupDeleteRequest.FromString,
                    response_serializer=sgrm__pb2.CompletionResponse.SerializeToString,
            ),
            'bulkDeleteLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.bulkDeleteLookup,
                    request_deserializer=sgrm__pb2.LookupBulkDeleteRequest.FromString,
                    response_serializer=sgrm__pb2.BulkOpCompletionResponse.SerializeToString,
            ),
            'readShuriOfsFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.readShuriOfsFeature,
                    request_deserializer=sgrm__pb2.ShuriOfsReadFeatureRequest.FromString,
                    response_serializer=sgrm__pb2.ShuriOfsReadResponse.SerializeToString,
            ),
            'readShuriOfsFeatureGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.readShuriOfsFeatureGroups,
                    request_deserializer=sgrm__pb2.ShuriOfsReadFeatureGroupsRequest.FromString,
                    response_serializer=sgrm__pb2.ShuriOfsReadResponse.SerializeToString,
            ),
            'writeShuriOfsFeatureGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.writeShuriOfsFeatureGroup,
                    request_deserializer=sgrm__pb2.ShuriOfsWriteFeatureGroupRequest.FromString,
                    response_serializer=sgrm__pb2.CompletionStatus.SerializeToString,
            ),
            'deleteShuriOfsFeatureField': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteShuriOfsFeatureField,
                    request_deserializer=sgrm__pb2.ShuriOfsDeleteFeatureFieldRequest.FromString,
                    response_serializer=sgrm__pb2.CompletionStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ResourceManagerProtoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResourceManagerProtoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def fetchA3Token(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/fetchA3Token',
            sgrm__pb2.A3TokenRequest.SerializeToString,
            sgrm__pb2.A3TokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def validateA3Token(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/validateA3Token',
            sgrm__pb2.A3TokenValidateRequest.SerializeToString,
            sgrm__pb2.A3TokenValidateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def publishError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/publishError',
            sgrm__pb2.ErrorRequest.SerializeToString,
            sgrm__pb2.ErrorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def readAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/readAttributes',
            sgrm__pb2.AttributesReadRequest.SerializeToString,
            sgrm__pb2.AttributesReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bulkReadAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/bulkReadAttributes',
            sgrm__pb2.AttributesBulkReadRequest.SerializeToString,
            sgrm__pb2.AttributesReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def readAttributesFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/readAttributesFields',
            sgrm__pb2.AttributesReadFieldsRequest.SerializeToString,
            sgrm__pb2.AttributesReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def readAttributesRangeFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/readAttributesRangeFields',
            sgrm__pb2.AttributesReadRangeFieldsRequest.SerializeToString,
            sgrm__pb2.AttributesReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def writeAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/writeAttributes',
            sgrm__pb2.AttributesWriteRequest.SerializeToString,
            sgrm__pb2.CompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bulkWriteAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/bulkWriteAttributes',
            sgrm__pb2.AttributesBulkWriteRequest.SerializeToString,
            sgrm__pb2.BulkOpCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def writeAttributesField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/writeAttributesField',
            sgrm__pb2.AttributesWriteRequest.SerializeToString,
            sgrm__pb2.CompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def writeAttributesFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/writeAttributesFields',
            sgrm__pb2.AttributesWriteRequest.SerializeToString,
            sgrm__pb2.CompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/deleteAttributes',
            sgrm__pb2.AttributesDeleteRequest.SerializeToString,
            sgrm__pb2.CompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bulkDeleteAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/bulkDeleteAttributes',
            sgrm__pb2.AttributesBulkDeleteRequest.SerializeToString,
            sgrm__pb2.BulkOpCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def readLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/readLookup',
            sgrm__pb2.LookupReadRequest.SerializeToString,
            sgrm__pb2.LookupReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bulkReadLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/bulkReadLookup',
            sgrm__pb2.LookupBulkReadRequest.SerializeToString,
            sgrm__pb2.LookupReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def writeLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/writeLookup',
            sgrm__pb2.LookupWriteRequest.SerializeToString,
            sgrm__pb2.CompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bulkWriteLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/bulkWriteLookup',
            sgrm__pb2.LookupBulkWriteRequest.SerializeToString,
            sgrm__pb2.BulkOpCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/deleteLookup',
            sgrm__pb2.LookupDeleteRequest.SerializeToString,
            sgrm__pb2.CompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bulkDeleteLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/bulkDeleteLookup',
            sgrm__pb2.LookupBulkDeleteRequest.SerializeToString,
            sgrm__pb2.BulkOpCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def readShuriOfsFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/readShuriOfsFeature',
            sgrm__pb2.ShuriOfsReadFeatureRequest.SerializeToString,
            sgrm__pb2.ShuriOfsReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def readShuriOfsFeatureGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/readShuriOfsFeatureGroups',
            sgrm__pb2.ShuriOfsReadFeatureGroupsRequest.SerializeToString,
            sgrm__pb2.ShuriOfsReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def writeShuriOfsFeatureGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/writeShuriOfsFeatureGroup',
            sgrm__pb2.ShuriOfsWriteFeatureGroupRequest.SerializeToString,
            sgrm__pb2.CompletionStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteShuriOfsFeatureField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceManagerProtoService/deleteShuriOfsFeatureField',
            sgrm__pb2.ShuriOfsDeleteFeatureFieldRequest.SerializeToString,
            sgrm__pb2.CompletionStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
