apiVersion: "stargate.aml.apple.com/v1"
kind: StargateDeployment
metadata:
  name: py-lookup
spec:
  deploymentSize: small
  logForwarder: default
  pythonImage: docker.apple.com/aml/stargate-python-non-embedded-example:latest

  definition:

    reader:
      name: GenerateTick
      type: Ticker
      config:
        schemaId: com.apple.aml.stargate.#{ENV}.internal.KeyValue
        frequency: 10s
        expression: |
          {
            "key" : "auto-${statics["java.util.UUID"].randomUUID()}",
            "value" : "${record.epoc}"
          }

    transformer:
      name: InvokeLambda
      type: Python
      logLevelIn: INFO
      config:
        functionOptions:
          file: /app/sampleapp/foo/bar/lookup.py
          class: LookupSample

    writer:
      name: DoNothing
      type: NoOp

    dag: "GenerateTick->InvokeLambda->DoNothing"