#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: stargate-spark-facade
#  namespace: stargate-flink

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stargate-spark-facade
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
      - "deletecollection"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stargate-spark-facade-binding
  namespace: stargate-flink
subjects:
  - kind: ServiceAccount
    name: stargate-spark-facade
    namespace: stargate-flink
roleRef:
  kind: ClusterRole
  name: stargate-spark-facade
  apiGroup: ""